CREATE TABLE `community_info` (
  `COM_IDX` int NOT NULL AUTO_INCREMENT,
  `USER_IDX` int NOT NULL,
  `TITLE` varchar(1000) NOT NULL,
  `CONTENT` varchar(1000) NOT NULL,
  `GOOD_COUNT` int DEFAULT '0',
  `WRITE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`COM_IDX`),
  KEY `COMMUNITY_INFO_USER_IDX_TO_USER_JOIN_USER_IDX_idx` (`USER_IDX`),
  CONSTRAINT `COMMUNITY_INFO_USER_IDX_TO_USER_JOIN_USER_IDX` FOREIGN KEY (`USER_IDX`) REFERENCES `user_join_info` (`USER_IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `user_join_info` (
  `USER_IDX` int NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(20) NOT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `USER_EMAIL` varchar(20) DEFAULT NULL,
  `USER_NICK` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

create table USER_COM_GOOD_MAP(
USER_IDX int,
COM_IDX int,
GOOD_YN boolean
);
